---
- name: Add jenkins repository key (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt_key:
    url: "{{ jenkins_apt_key_url }}"

- name: Add jenkins apt-repository (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: "{{ jenkins_apt_repo }}"

- name: Add jenkins yum-repository (RedHat)
  when: ansible_os_family == "RedHat"
  yum_repository:
    name: jenkins-stable
    description: Jenkins CI Stable
    baseurl: "{{ jenkins_yum_repo }}"
    gpgkey: "{{ jenkins_yum_key_url }}"
    gpgcheck: yes
